version: 2
updates:
  # npm / pnpm dependencies in the root and workspaces
  - package-ecosystem: "npm"
    directory: "/"            # root directory
    schedule:
      interval: "weekly"      # can be "daily", "weekly", "monthly"
      day: "friday"
      time: "12:00"           # UTC time; 13:00 in Madrid winter / 14:00 summer
    open-pull-requests-limit: 10
    cooldown:
      # semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
    ignore:
      # ignore major updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore(deps)"
    groups:
      tooling:
        patterns:
          - "eslint*"
          - "prettier"
          - "typescript"
          - "@babel/*"
          - "@types/*"
          - "get-tsconfig"
      testing:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "vitest"
          - "playwright*"
      infra:
        patterns:
          - "wrangler"
      everything-else:
        patterns:
          - "*"
